# Generated by Django 5.0.4 on 2024-04-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('magster', 'Magister'), ('bakalavr', 'Bakalavr')], default='bakalavr', max_length=100),
        ),
    ]
